### ISSUE TITLE
continue used outside of loop

### ISSUE THREAD

**Issue by ilyash-b** [aws-samples/ci-4-terraform-aws-developer-tools-terratest#4]
https://github.com/aws-samples/ci-4-terraform-aws-developer-tools-terratest/blob/e0eec9e6ad4e84bb0b5c543a44e7ae1ffaf874d6/terraform/examples/cicd_account/run_terraform.sh#L22

My IDE gives:

"continue is only valid in loops.", see https://github.com/koalaman/shellcheck/wiki/SC2105

**Comment by luchetto81** [comment]
Thanks for your contribute. Addressing it

**Comment by luchetto81** [comment]
Fixed in release v0.2.0
