### ISSUE TITLE
Typo in terraform/examples/cicd_account/run_terraform.sh:1

### ISSUE THREAD

**Issue by ilyash-b** [aws-samples/ci-4-terraform-aws-developer-tools-terratest#5]
"Use #!, not just #, for the shebang."

https://github.com/koalaman/shellcheck/wiki/SC1113

**Comment by luchetto81** [comment]
Thanks so much for your contribute.
I'll fix immediately

**Comment by luchetto81** [comment]
This has been fixed in release v0.2.0
